config/routes.rb
Dinner::Application.routes.draw do
  get '/' => 'public#random'
  get '/new' => 'public#new'
  post '/create' => 'public#create'
  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  http_basic_authenticate_with name: "sxsw", password: "2014"

  layout 'admin'

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :link, :category)
    end
end

app/controllers/public_controller.rb
require 'open-uri'
require 'json'

class PublicController < ApplicationController
  def random
    num_items = Item.count
    offset_items = Item.offset(rand(num_items))
    @item = offset_items.first

    url = "http://www.loc.gov/pictures/search/?q=#{@item.category}&fo=json"
    response = open(url).read
    parsed_response = JSON.parse(response)
    results = parsed_response["results"]

    random_num = rand(results.count)
    result = results[random_num]

    if (result['image']['alt'].include? "not digitized") || (result['image']['alt'].include? "Look magazine")
      @image_url = "http://cdn.sheknows.com/articles/2011/02/Fork_knife_and_plate.jpg"
    else
      @image_url = result["image"]["full"]
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new
    @item.title = params[:item][:title]
    @item.description = params[:item][:description]
    @item.link = params[:item][:link]
    @item.category = params[:item][:category]

    respond_to do |format|
      if @item.save
        format.html { redirect_to new_path, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<ol class="breadcrumb">
    <li><%= link_to 'All items', items_path %></li>
    <li><%= link_to @item.title, item_path %></li>
</ol>

<div class="page-header">
    <h1>Edit <%= @item.title %></h1>
</div>

<%= render 'form' %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<p>
<%= link_to 'New Item', new_item_path, {:class => "btn btn-default" } %>
</p>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Link</th>
      <th>Category</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.description %></td>
        <td><%= item.link %></td>
        <td><%= item.category %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/items/new.html.erb
<ol class="breadcrumb">
    <li><%= link_to 'All items', items_path %></li>
</ol>

<div class="page-header">
    <h1>New item</h1>
</div>

<%= render 'form' %>

app/views/items/show.html.erb
<ol class="breadcrumb">
    <li><%= link_to 'All items', items_path %></li>
</ol>

<% if notice %>
<p class="alert alert-success"><%= notice %></p>
<% end %>

<div class="page-header">
    <h1>
      <%= @item.title %>
    </h1>
</div>

<p class="desc">
  <%= @item.description %>
</p>

<p>
  <%= link_to @item.link, @item.link %><br>
  <strong>Category:</strong> <%= @item.category %>
</p>

<p>
    <%= link_to 'Edit this', edit_item_path(@item), {:class => "btn btn-default"} %>
</p>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>DinnerApp</title>
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<link rel="stylesheet" type="text/css" href="/assets/bootstrap.min.css">
<%= csrf_meta_tags %>
</head>
<body class="admin">

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dinner</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Coustard:400,900' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="public">

<%= yield %>

</body>
</html>